export { default as Code } from './Code'
export { default as Heading } from './Heading'
export { default as P } from './P'
export { default as Pre } from './Pre'
export { default as TOCInline } from './TOCInline'
